blank_issues_enabled: false
contact_links:
  - name: 'GitHub'
    url: https://github.com/anguspiv/www.angusp.com/discussions
    about: 'Ask questions, share ideas, and get help from the community.'
