name: Feature Request
description: 'Suggest a new feature or improvement.'
title: '[Feature Request]: '
labels:
  - 'feature'
  - 'needs-triage'
projects:
  - anguspiv/2
  - anguspiv/11
assignees:
  - 'anguspiv'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature or improvement! Please fill out the details below.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the feature is.
      placeholder: 'I would like to see...'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the problem you're facing or the improvement you're suggesting.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List any requirements or dependencies for the feature.
      placeholder: 'This feature requires...'
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request.
      placeholder: 'Here is a screenshot...'
    validations:
      required: false
