name: Build and Test

on:
  push:
    branches-ignore:
      - master

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{secrets.FONTAWESOME_NPM_AUTH_TOKEN}}
  GHOST_API_URL: ${{secrets.GHOST_API_URL}}
  GHOST_CONTENT_API_URL: ${{secrets.GHOST_CONTENT_API_URL}}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodes.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
