name: Release
on:
  push:
    branches:
      - master

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{secrets.FONTAWESOME_NPM_AUTH_TOKEN}}

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodes.js
        uses: actions/setup-node@v2
        with:
          node-versions: 16
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
